### ISSUE TITLE
Warning in test releases: no deobfuscation file

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.noi.community.android#28]
Google shows:
```
Warning
There is no deobfuscation file associated with this App Bundle. If you use obfuscated code (R8/proguard), uploading a deobfuscation file will make crashes and ANRs easier to analyse and debug. Using R8/proguard can help reduce app size.

https://developer.android.com/studio/build/shrink-code#decode-stack-trace
```

What should we do to get rid of this warning?

**Comment by macteo** [comment]
The compilation step creates a mapping file to deobfuscate the code. 
The GitHub action should be updated to grab this file generated at compile time and upload it to Play Store alongside the app bundle.
I’ll let @stezan add more informations on this topic.

**Comment by Piiit** [comment]
Thx... I commented that file out at the moment, because it was not generated...

**Comment by stezan** [comment]
the mapping file is the file used for the automatic deobfuscation, when you compile the application in release it is automatically generated

```
with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: it.bz.noi.community
          releaseFiles: ${{ steps.sign_app.outputs.signedReleaseFile }}
          track: internal
          status: draft
          #mappingFile: mapping-${{ github.sha }}.txt
```

I saw that you placed a comment near `mappingFile: mapping-${{ github.sha }}.txt`. Why? Maybe is it the wrong path?
